
Parameters:

  TwitterTokenKey:
    Type: String
    Description: twitter token key

  TwitterTokenSecret:
    Type: String
    Description: twitter token secret

  TwitterConsumerKey:
    Type: String
    Description: twitter consumer key

  TwitterConsumerSecret:
    Type: String
    Description: twitter consumer secret

  CreateAnimationArn:
    Type: String
    Description: lambda arn for creating the animation

Resources:

  LambdaPermissionSNS:
    Type: "AWS::Lambda::Permission"
    Properties:
      FunctionName:
        !GetAtt LambdaTweet.Arn
      Action: "lambda:InvokeFunction"
      Principal: "sns.amazonaws.com"

  LambdaGlobalRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: "inline-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
              -
                Effect: "Allow"
                Action:
                  - lambda:InvokeFunction
                Resource: "*"

  SNSTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      DisplayName: !Sub ${AWS::StackName}_TwitterHelper
      Subscription:
        -
          Endpoint: !GetAtt LambdaTweet.Arn
          Protocol: lambda
      TopicName: "TwitterHelper"


  LambdaTweet:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        ZipFile: |
          def handler(event, context):
            print(event)
            return None
      Description: tweets
      FunctionName:
        !Sub ${AWS::StackName}_Tweet
      Handler: index.handler
      MemorySize: 128
      Role:
        !GetAtt LambdaGlobalRole.Arn
      Runtime: python2.7
      Timeout: 120
      Environment:
        Variables:
          token_key: !Ref TwitterTokenKey
          token_secret: !Ref TwitterTokenSecret
          consumer_key: !Ref TwitterConsumerKey
          consumer_secret: !Ref TwitterConsumerSecret
          create_animation_arn: !Ref CreateAnimationArn
